config/routes.rb
Rails.application.routes.draw do
  resources :rooms

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_room
    Room.find(cookies[:room_id]) || Room.new
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  protect_from_forgery :except => [:create]

  before_action :find_room, except: :index

  def show
    @messages = @room.messages
  end

  def index
    @rooms = Room.all
  end

  def create
    @msg = @room.messages.create(content: params[:content])
    ActionCable.server.broadcast "room_id_#{@msg.room_id}", message: render_message(@msg)
    head :ok
  end

  private
  def find_room
    @room = Room.find(params[:id])
    cookies[:room_id] = @room.try(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class=“message”>
  <p><%= message.content %></p>
</div>

app/views/rooms/index.html.erb
<ul>
  <% @rooms.each do |room| %>
    <li><%= link_to room.title, room_path(room) %></li>
  <% end if @rooms.any? %>
</ul>

app/views/rooms/show.html.erb
<h3>Count of msg in room: <span id="room_<%=@room.id%>_msg_count"><%= @room.messages.count %></span></h3>
<h1>Chat room</h1>
<div id="messages">
  <%= render @messages %>
</div>
<form>
  <label>Say something:</label><br>
  <%= hidden_field_tag 'room_id', @room.id, id: 'room_id' %>
  <input type="text" data-behavior="room_speaker">
</form>